<%@ Page Title="" Language="C#" MasterPageFile="~/view/Main.Master" AutoEventWireup="true" CodeBehind="InactiveUser.aspx.cs" Inherits="ServiceDesk.view.InactiveUser" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="aspAjax" %>
<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <script type="text/javascript">
         function RedirectPage() {
             window.parent.location = 'AddUser.aspx';
         }
    </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <telerik:radskinmanager ID="QsfSkinManager" runat="server" ShowChooser="false" Skin="Sitefinity" />
    <telerik:radscriptmanager ID="ScriptManager1" runat="server" ScriptMode="Release"></telerik:radscriptmanager>
    <style>
        .rgRow {
            background-color:white;
            color:black;
        }
            .rgRow a {
                color:black!important;
            }

        .rgAltRow {
            background-color:#33A1C9 !important;
            color:white;
        }
    </style>
    <div style ="text-align:center;" align="center"><br />
        <table style="width:100%;" align="center">
            <tr style="text-align:left;">
                <td style="width:790px;">
                    <a href="#" class="LblControl" onclick="RedirectPage();">View Add User</a><br /><br /></td>
            </tr>           
            <tr>
                <td colspan="2" align ="center" >
                    <!--DivGridview-->
                    <div >
                        <telerik:RadGrid ID="userGV" runat="server" AllowAutomaticDeletes="True"  skin ="Black"
                            AllowAutomaticInserts="false" AllowAutomaticUpdates="True"
                            AllowFilteringByColumn="true" AllowPaging="false" AllowSorting="True"
                            AutoGenerateDeleteColumn="True" EnableAriaSupport="True" EnableHeaderContextMenu="True"
                            EnableHierarchyExpandAll="True" RetainExpandStateOnRebind="True" OnNeedDataSource="userGV_NeedDataSource"
                            ShowFooter="true" ShowGroupPanel="false" ShowStatusBar="false" OnDeleteCommand="userGV_DeleteCommand" OnItemCreated="userGV_ItemCreated"
                            OnItemDataBound="userGV_ItemDataBound">
                            <PagerStyle Mode="NextPrevAndNumeric" />
                            <GroupingSettings CaseSensitive="false" />
                            <MasterTableView EnableGroupsExpandAll="True" EnableHeaderContextAggregatesMenu="False" DataKeyNames="Login_ID"
                                AutoGenerateColumns="false">
                                <Columns>
                                    <telerik:GridBoundColumn UniqueName="Login_ID" HeaderText="Login ID" DataField="Login_ID" AllowFiltering="false" HeaderStyle-Width="100"></telerik:GridBoundColumn>
                                    <telerik:GridBoundColumn UniqueName="NTID" HeaderText="NT ID" DataField="NT_ID" AllowFiltering="true"></telerik:GridBoundColumn>
                                    <telerik:GridBoundColumn UniqueName="FirstName" HeaderText="First Name" DataField="First_Name" AllowFiltering="true"></telerik:GridBoundColumn>
                                    <telerik:GridBoundColumn UniqueName="LastName" HeaderText="Last Name" DataField="Last_Name" AllowFiltering="true"></telerik:GridBoundColumn>
                                    <telerik:GridBoundColumn UniqueName="RollID" HeaderText="Roll ID" DataField="Roll_ID" AllowFiltering="false"></telerik:GridBoundColumn>
                                    <telerik:GridBoundColumn UniqueName="RollName" HeaderText="Roll Name" DataField="Roll_Name" Visible="false"></telerik:GridBoundColumn>
                                    <telerik:GridBoundColumn UniqueName="UserStatus" HeaderText="User Status" DataField="user_status" AllowFiltering="true"></telerik:GridBoundColumn>                                    
                                </Columns>
                            </MasterTableView>
                        </telerik:RadGrid>
                    </div>
                    <!--DivGridview-->
                </td>
            </tr>
        </table>

        <style type="text/css">
            div.RadWindow {
                z-index: 9000 !important;
            }

            .modalBackground {
                background-color: Gray;
                filter: alpha(opacity=70);
                opacity: 0.7;
            }

            .modalPopup {
                background-color: #4f4f4f;
                border-width: 3px;
                border-style: solid;
                border-color: Gray;
                padding: 3px;
                width: 450px;
                color:white;
            }

            .rgEditForm {
                background-color: white;
                color: black;
            }
        </style>
    </div>
</asp:Content>
